spring.datasource.url=jdbc:sqlite:D:/Flutter_Projects/AshaSathi/data/ashasathi.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# If you have a custom dialect class, use the class name here; otherwise remove this line.
#spring.jpa.properties.hibernate.dialect=com.Rahul.AshaSathi.Config.SQLiteDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
