import 'package:flutter/material.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static const List<Locale> supportedLocales = <Locale>[
    Locale('en'),
    Locale('hi'),
    Locale('bn'),
    Locale('te'),
    Locale('mr'),
    Locale('ta'),
    Locale('gu'),
  ];

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static AppLocalizations of(BuildContext context) {
    final localizations = Localizations.of<AppLocalizations>(
      context,
      AppLocalizations,
    );
    assert(localizations != null, 'AppLocalizations not found in widget tree');
    return localizations!;
  }

  static const Map<String, String> nativeLanguageNames = {
    'en': 'English',
    'hi': 'Hindi',
    'bn': 'Bengali',
    'te': 'Telugu',
    'mr': 'Marathi',
    'ta': 'Tamil',
    'gu': 'Gujarati',
  };

  static const Map<String, String> nativeLanguageScripts = {
    'en': 'English',
    'hi': 'हिन्दी',
    'bn': 'বাংলা',
    'te': 'తెలుగు',
    'mr': 'मराठी',
    'ta': 'தமிழ்',
    'gu': 'ગુજરાતી',
  };

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app.name': 'AshaSathi',
      'common.cancel': 'Cancel',
      'common.back': 'Back',
      'common.next': 'Next',
      'common.confirm': 'Confirm',
      'common.errorWithMessage': 'Error: {error}',
      'common.confirmSelection': 'Confirm Selection',
      'common.delete': 'Delete',
      'common.clear': 'Clear',
      'common.view': 'View',
      'common.viewAll': 'View All',
      'common.settings': 'Settings',
      'common.language': 'Language',
      'common.selectLanguage': 'Select Language',
      'common.languageHint':
          'Choose your preferred language to customize your experience.',
      'common.required': 'Required',
      'theme.switchToLight': 'Switch to light mode',
      'theme.switchToDark': 'Switch to dark mode',
      'auth.welcomeBack': 'Welcome Back \nAsha Sathi',
      'auth.loginSubtitle':
          'Sign in to support your community with better healthcare tracking',
      'auth.email': 'Email',
      'auth.emailAddress': 'Email Address',
      'auth.password': 'Password',
      'auth.login': 'Login',
      'auth.orLoginWith': 'Or Login with',
      'auth.orContinueWith': 'Or Continue With',
      'auth.dontHaveAccount': "Don't have an account?",
      'auth.createNewAccount': 'Create new account',
      'auth.createAccount': 'Create Account',
      'auth.google': 'Google',
      'auth.createNewAshaAccount': 'Create New \nAsha Account',
      'auth.username': 'Username',
      'auth.phoneNumber': 'Phone Number',
      'auth.create': 'Create',
      'auth.orSignupWith': 'Or Sign up with',
      'auth.alreadyHaveAccount': 'Already have an account?',
      'home.welcome': 'Welcome,\n',
      'home.ashaWorker': 'Asha Worker!',
      'home.dailyOverview': 'Your daily health overview is ready',
      'home.dailyTasks': 'Daily Tasks',
      'home.recentPatients': 'Recent Patients',
      'home.noTasksToday': 'No tasks for today',
      'home.noPatientsFound': 'No patients found',
        'sync.statusTitle': 'Sync Status',
        'sync.syncingNow': 'Sync in progress',
        'sync.statusSummary':
          'Queue (pending+delete): {queue} | Failed retries: {retry} | Conflicts: {conflicts}',
        'sync.retryNow': 'Retry Now',
        'sync.resolveConflicts': 'Resolve Conflicts',
        'sync.conflictsTitle': 'Sync Conflicts',
        'sync.noConflicts': 'No sync conflicts',
        'sync.localValue': 'Local',
        'sync.serverValue': 'Server',
        'sync.localNotes': 'Local notes',
        'sync.serverNotes': 'Server notes',
        'sync.keepLocal': 'Keep Local',
        'sync.keepServer': 'Keep Server',
        'sync.conflictResolvedLocal': 'Conflict resolved: kept local changes',
        'sync.conflictResolvedServer': 'Conflict resolved: kept server values',
      'home.settings': 'Settings',
      'home.language': 'Language',
      'nav.dashboard': 'Dashboard',
      'nav.addPatient': 'Add Patient',
      'nav.phcPortal': 'PHC Portal',
      'nav.dashboardTitle': 'ASHA Dashboard',
      'drawer.logout': 'Logout',
      'task.addNewTask': 'Add New Task',
      'task.editTask': 'Edit Task',
      'task.createNewTask': 'Create New Task',
      'task.updateTask': 'Update Task',
      'task.taskTitle': 'Task Title',
      'task.taskTitleHint': 'e.g., Patient Follow-up',
      'task.taskDescription': 'Task Description',
      'task.taskDescriptionHint': 'Describe the task...',
      'task.status': 'Status',
      'task.saveTask': 'Save Task',
      'task.pleaseEnterTitle': 'Please enter a task title',
      'task.addedSuccessfully': 'Task added successfully!',
      'task.updatedSuccessfully': 'Task updated successfully!',
      'task.urgent': 'Urgent',
      'task.pending': 'Pending',
      'task.inProgress': 'In Progress',
      'task.completed': 'Completed',
      'task.done': 'Done',
      'task.deleteTask': 'Delete Task',
      'task.deleteTaskConfirm': 'Are you sure you want to delete this task?',
      'task.deletedSuccessfully': 'Task deleted successfully',
      'task.markedDeletion': 'Task marked for deletion (will sync later)',
      'task.errorDeleting': 'Error deleting task: {error}',
      'patient.addPhoto': 'Add Photo',
      'patient.patientName': 'Patient Name',
      'patient.age': 'Age',
      'patient.address': 'Address',
      'patient.dateOfBirth': 'Date of Birth',
      'patient.selectDate': 'Select date',
      'patient.gender': 'Gender',
      'patient.female': 'Female',
      'patient.male': 'Male',
      'patient.other': 'Other',
      'patient.saveData': 'Save Patient Data',
      'patient.pleaseAddPhoto': 'Please add a patient photo',
      'patient.invalidName': 'Enter a valid patient name',
      'patient.invalidAge': 'Enter a valid age between 1 and 130',
      'patient.invalidAddress': 'Enter a complete address',
      'patient.invalidPhone': 'Enter a valid 10-digit phone number',
      'patient.invalidDob': 'Select a valid date of birth',
      'patient.saveSuccessOnline': 'Patient saved and synced successfully',
      'patient.saveSuccessOffline': 'Patient saved offline and will sync later',
      'patient.saveFailed': 'Unable to save patient. Please try again.',
      'patient.takePhoto': 'Take Photo',
      'patient.chooseFromGallery': 'Choose from Gallery',
      'patient.saved': 'Patient Saved',
      'patient.savedDetails': 'Details recorded successfully',
      'patient.details': 'Patient Details',
        'patient.stepFamily': 'Family',
        'patient.stepPatient': 'Patient',
        'patient.stepMedical': 'Medical',
        'patient.sessionExpiredLogin': 'Session expired. Please login again.',
        'patient.familyRegisteredSuccess': 'Family registered successfully!',
        'patient.saveFailedTryAgain': 'Failed to save. Please try again.',
        'patient.familyInformation': 'Family Information',
        'patient.headOfFamilyRequired': 'Head of Family *',
        'patient.enterHeadOfFamily': 'Enter Head of Family *',
        'patient.numberOfMembers': 'Number of Members',
        'patient.familyAddressRequired': 'Family Address *',
        'patient.enterFamilyAddress': 'Enter Family Address *',
        'patient.useAddressForAllFamilyMembers':
          'Use this address for all family members',
        'patient.familyInfoHelpText':
          'Enter the family head\'s name and the total number of family members to register. The family address will be used by default for all members unless specified otherwise.',
        'patient.patientNameRequired': 'Patient Name *',
        'patient.caste': 'Caste',
        'patient.memberWithIndex': 'Member {index}',
        'patient.changePhoto': 'Change Photo',
        'patient.removePhoto': 'Remove Photo',
        'patient.removeMemberTitle': 'Remove Member?',
        'patient.removeMemberPromptDefault': 'Remove this member?',
        'patient.removeMemberPromptNamed': 'Remove {name}?',
        'patient.remove': 'Remove',
        'patient.removeThisMember': 'Remove This Member',
        'patient.isPregnant': 'Is Pregnant?',
        'patient.expectedDeliveryDate': 'Expected Delivery Date',
        'patient.monthsOfPregnancy': 'Months of Pregnancy',
        'patient.monthsCount': '{count} month(s)',
        'patient.sameAsFamilyAddress': 'Same as family address',
        'patient.patientAddress': 'Patient Address',
        'patient.medicalInformation': 'Medical Information',
        'patient.privacyDeclined':
          'Patient prefers not to share medical information',
        'patient.privacyDeclinedBanner':
          'Patient has declined to share medical information',
        'patient.selectHealthConditions': 'Select Health Conditions',
        'patient.additionalNotes': 'Additional Notes',
        'patient.additionalNotesHint':
          'Add any additional notes about the patient...',
        'patient.summary': 'Summary',
        'patient.totalPatients': 'Total patients: {count}',
        'patient.conditionsSelected': 'Conditions selected: {count}',
        'patient.privacyDeclinedSummary':
          'Privacy: Patient declined to share health info',
        'patient.condition.bp': 'BP',
        'patient.condition.elephantiasis': 'Elephantiasis',
        'patient.condition.diabetes': 'Diabetes',
        'patient.condition.heartDisease': 'Heart Disease',
        'patient.condition.asthma': 'Asthma',
        'patient.condition.thyroid': 'Thyroid',
        'patient.condition.arthritis': 'Arthritis',
        'patient.condition.kidney': 'Kidney',
        'patient.condition.liver': 'Liver',
        'patient.condition.cancer': 'Cancer',
      'patient.ageYears': '{age} years',
      'patient.phone': 'Phone',
      'patient.delete': 'Delete Patient',
      'patient.deleteConfirm':
          'This will delete the patient. You can sync later if offline.',
      'patient.markedDeletion':
          'Patient marked for deletion (will sync when online)',
      'patient.deletedSuccessfully': 'Patient deleted successfully',
      'patient.deleteFailedStatus': 'Delete failed: {status}. Will sync later',
      'patient.errorDeleting': 'Error deleting: {error}. Will sync later',
      'patients.title': 'Patients',
      'patients.searchHint': 'Search by name or ID...',
      'patients.quickFilters': 'QUICK FILTERS',
      'patients.allGender': 'All Gender',
      'patients.others': 'Others',
      'patients.age18to35': 'Age: 18-35',
      'patients.recentRecords': 'Recent Records ({count})',
      'patients.showingAll': 'Showing all registered patients',
      'patients.filtersHint':
          'Use filters above to refine your search or add a new patient record.',
      'patients.newest': 'Newest',
      'patients.oldest': 'Oldest',
      'patients.nameAZ': 'Name (A-Z)',
      'patients.sortBy': 'Sort by: {sort}',
      'patients.yearsShort': '{age} yrs',
      'phc.keyMetrics': 'Key Metrics',
      'phc.totalPatients': 'Total Patients',
      'phc.genderDistribution': 'Gender Distribution',
    },
    'hi': {
      'app.name': 'आशासाथी',
      'common.cancel': 'रद्द करें',
      'common.back': 'वापस',
      'common.next': 'आगे',
      'common.confirm': 'पुष्टि करें',
      'common.errorWithMessage': 'त्रुटि: {error}',
      'common.confirmSelection': 'चयन की पुष्टि करें',
      'common.delete': 'हटाएं',
      'common.clear': 'साफ करें',
      'common.view': 'देखें',
      'common.viewAll': 'सभी देखें',
      'common.settings': 'सेटिंग्स',
      'common.language': 'भाषा',
      'common.selectLanguage': 'भाषा चुनें',
      'common.required': 'आवश्यक',
      'common.languageHint': 'अपने अनुभव को अनुकूलित करने के लिए भाषा चुनें।',
      'auth.welcomeBack': 'वापसी पर स्वागत है \nआशा साथी',
      'auth.email': 'ईमेल',
      'auth.password': 'पासवर्ड',
      'auth.login': 'लॉगिन',
      'auth.orLoginWith': 'या इससे लॉगिन करें',
      'auth.dontHaveAccount': 'खाता नहीं है?',
      'auth.createNewAccount': 'नया खाता बनाएं',
      'auth.createNewAshaAccount': 'नया \nआशा खाता बनाएं',
      'auth.username': 'यूज़रनेम',
      'auth.phoneNumber': 'फोन नंबर',
      'auth.create': 'बनाएं',
      'auth.orSignupWith': 'या इससे साइन अप करें',
      'auth.alreadyHaveAccount': 'क्या आपके पास पहले से खाता है?',
      'home.settings': 'सेटिंग्स',
      'home.language': 'भाषा',
      'home.welcome': 'स्वागत है,\n',
      'home.ashaWorker': 'आशा कार्यकर्ता!',
      'home.dailyOverview': 'आपका दैनिक स्वास्थ्य सारांश तैयार है',
      'home.dailyTasks': 'दैनिक कार्य',
      'home.recentPatients': 'हाल के मरीज',
      'home.noTasksToday': 'आज के लिए कोई कार्य नहीं',
      'home.noPatientsFound': 'कोई मरीज नहीं मिला',
      'nav.dashboard': 'डैशबोर्ड',
      'nav.addPatient': 'मरीज जोड़ें',
      'nav.phcPortal': 'पीएचसी पोर्टल',
      'nav.dashboardTitle': 'आशा डैशबोर्ड',
      'drawer.logout': 'लॉग आउट',
      'task.addNewTask': 'नया कार्य जोड़ें',
      'task.editTask': 'कार्य संपादित करें',
      'task.createNewTask': 'नया कार्य बनाएं',
      'task.updateTask': 'कार्य अपडेट करें',
      'task.taskTitle': 'कार्य शीर्षक',
      'task.taskDescription': 'कार्य विवरण',
      'task.status': 'स्थिति',
      'task.saveTask': 'कार्य सहेजें',
      'task.pleaseEnterTitle': 'कार्य का शीर्षक दर्ज करें',
      'task.addedSuccessfully': 'कार्य सफलतापूर्वक जोड़ा गया!',
      'task.updatedSuccessfully': 'कार्य सफलतापूर्वक अपडेट किया गया!',
      'task.urgent': 'अति आवश्यक',
      'task.pending': 'लंबित',
      'task.inProgress': 'प्रगति पर',
      'task.completed': 'पूर्ण',
      'task.done': 'पूर्ण',
      'task.deleteTask': 'कार्य हटाएं',
      'task.deleteTaskConfirm': 'क्या आप यह कार्य हटाना चाहते हैं?',
      'task.deletedSuccessfully': 'कार्य सफलतापूर्वक हटाया गया',
      'task.markedDeletion': 'कार्य हटाने के लिए चिह्नित (बाद में सिंक होगा)',
      'patient.addPhoto': 'फोटो जोड़ें',
      'patient.patientName': 'मरीज का नाम',
      'patient.age': 'आयु',
      'patient.address': 'पता',
      'patient.dateOfBirth': 'जन्म तिथि',
      'patient.selectDate': 'तिथि चुनें',
      'patient.gender': 'लिंग',
      'patient.female': 'महिला',
      'patient.male': 'पुरुष',
      'patient.other': 'अन्य',
      'patient.saveData': 'मरीज का डेटा सहेजें',
      'patient.pleaseAddPhoto': 'कृपया मरीज की फोटो जोड़ें',
      'patient.invalidName': 'कृपया मरीज का सही नाम दर्ज करें',
      'patient.invalidAge': 'कृपया 1 से 130 के बीच सही आयु दर्ज करें',
      'patient.invalidAddress': 'कृपया पूरा पता दर्ज करें',
      'patient.invalidPhone': 'कृपया सही 10 अंकों का फोन नंबर दर्ज करें',
      'patient.invalidDob': 'कृपया सही जन्म तिथि चुनें',
      'patient.saveSuccessOnline': 'मरीज का डेटा सफलतापूर्वक सहेजा और सिंक किया गया',
      'patient.saveSuccessOffline': 'मरीज का डेटा ऑफलाइन सहेजा गया, बाद में सिंक होगा',
      'patient.saveFailed': 'मरीज का डेटा सहेजा नहीं जा सका। कृपया फिर से प्रयास करें।',
      'patient.takePhoto': 'फोटो लें',
      'patient.chooseFromGallery': 'गैलरी से चुनें',
      'patient.saved': 'मरीज सहेजा गया',
      'patient.savedDetails': 'विवरण सफलतापूर्वक दर्ज हुए',
      'patient.details': 'मरीज विवरण',
        'patient.stepFamily': 'परिवार',
        'patient.stepPatient': 'मरीज',
        'patient.stepMedical': 'मेडिकल',
        'patient.sessionExpiredLogin': 'सेशन समाप्त हो गया। कृपया दोबारा लॉगिन करें।',
        'patient.familyRegisteredSuccess': 'परिवार सफलतापूर्वक पंजीकृत हुआ!',
        'patient.saveFailedTryAgain': 'सहेजा नहीं जा सका। कृपया फिर से प्रयास करें।',
        'patient.familyInformation': 'परिवार की जानकारी',
        'patient.headOfFamilyRequired': 'परिवार प्रमुख का नाम *',
        'patient.enterHeadOfFamily': 'परिवार प्रमुख का नाम दर्ज करें *',
        'patient.numberOfMembers': 'सदस्यों की संख्या',
        'patient.familyAddressRequired': 'परिवार का पता *',
        'patient.enterFamilyAddress': 'परिवार का पता दर्ज करें *',
        'patient.useAddressForAllFamilyMembers':
          'यह पता सभी परिवार सदस्यों के लिए उपयोग करें',
        'patient.familyInfoHelpText':
          'परिवार प्रमुख का नाम और कुल सदस्यों की संख्या दर्ज करें। जब तक अलग से न दिया जाए, परिवार का पता सभी सदस्यों के लिए उपयोग होगा।',
        'patient.patientNameRequired': 'मरीज का नाम *',
        'patient.caste': 'जाति',
        'patient.memberWithIndex': 'सदस्य {index}',
        'patient.changePhoto': 'फोटो बदलें',
        'patient.removePhoto': 'फोटो हटाएं',
        'patient.removeMemberTitle': 'सदस्य हटाएं?',
        'patient.removeMemberPromptDefault': 'क्या इस सदस्य को हटाना है?',
        'patient.removeMemberPromptNamed': 'क्या {name} को हटाना है?',
        'patient.remove': 'हटाएं',
        'patient.removeThisMember': 'इस सदस्य को हटाएं',
        'patient.isPregnant': 'क्या गर्भवती हैं?',
        'patient.expectedDeliveryDate': 'अपेक्षित प्रसव तिथि',
        'patient.monthsOfPregnancy': 'गर्भावस्था के महीने',
        'patient.monthsCount': '{count} महीना',
        'patient.sameAsFamilyAddress': 'परिवार के पते जैसा',
        'patient.patientAddress': 'मरीज का पता',
        'patient.medicalInformation': 'चिकित्सा जानकारी',
        'patient.privacyDeclined': 'मरीज चिकित्सा जानकारी साझा नहीं करना चाहता/चाहती',
        'patient.privacyDeclinedBanner':
          'मरीज ने चिकित्सा जानकारी साझा करने से मना किया है',
        'patient.selectHealthConditions': 'स्वास्थ्य स्थितियां चुनें',
        'patient.additionalNotes': 'अतिरिक्त नोट्स',
        'patient.additionalNotesHint': 'मरीज के बारे में अतिरिक्त नोट्स लिखें...',
        'patient.summary': 'सारांश',
        'patient.totalPatients': 'कुल मरीज: {count}',
        'patient.conditionsSelected': 'चयनित स्थितियां: {count}',
        'patient.privacyDeclinedSummary':
          'गोपनीयता: मरीज ने स्वास्थ्य जानकारी साझा करने से मना किया',
        'patient.condition.bp': 'बीपी',
        'patient.condition.elephantiasis': 'हाथीपांव',
        'patient.condition.diabetes': 'मधुमेह',
        'patient.condition.heartDisease': 'हृदय रोग',
        'patient.condition.asthma': 'अस्थमा',
        'patient.condition.thyroid': 'थायरॉइड',
        'patient.condition.arthritis': 'गठिया',
        'patient.condition.kidney': 'किडनी',
        'patient.condition.liver': 'लिवर',
        'patient.condition.cancer': 'कैंसर',
      'patient.phone': 'फोन',
      'patient.delete': 'मरीज हटाएं',
      'patients.title': 'मरीज',
      'patients.searchHint': 'नाम या आईडी से खोजें...',
      'patients.quickFilters': 'त्वरित फिल्टर',
      'patients.allGender': 'सभी लिंग',
      'patients.others': 'अन्य',
      'patients.age18to35': 'आयु: 18-35',
      'patients.recentRecords': 'हाल के रिकॉर्ड ({count})',
      'patients.showingAll': 'सभी पंजीकृत मरीज दिखाए जा रहे हैं',
      'patients.newest': 'नवीनतम',
      'patients.oldest': 'पुराने',
      'patients.sortBy': 'क्रमबद्ध करें: {sort}',
      'patients.yearsShort': '{age} वर्ष',
      'phc.keyMetrics': 'मुख्य संकेतक',
      'phc.totalPatients': 'कुल मरीज',
      'phc.genderDistribution': 'लिंग वितरण',
    },
    'bn': {
      'app.name': 'আশাসাথী',
      'common.cancel': 'বাতিল',
      'common.back': 'ফিরে যান',
      'common.next': 'পরবর্তী',
      'common.confirm': 'নিশ্চিত করুন',
      'common.errorWithMessage': 'ত্রুটি: {error}',
      'common.confirmSelection': 'নির্বাচন নিশ্চিত করুন',
      'common.delete': 'মুছুন',
      'common.clear': 'পরিষ্কার করুন',
      'common.view': 'দেখুন',
      'common.viewAll': 'সব দেখুন',
      'common.settings': 'সেটিংস',
      'common.language': 'ভাষা',
      'common.selectLanguage': 'ভাষা নির্বাচন করুন',
      'common.required': 'প্রয়োজনীয়',
      'common.languageHint': 'অভিজ্ঞতা কাস্টমাইজ করতে পছন্দের ভাষা বেছে নিন।',
      'theme.switchToLight': 'লাইট মোডে যান',
      'theme.switchToDark': 'ডার্ক মোডে যান',
      'auth.welcomeBack': 'ফিরে আসায় স্বাগতম \nআশা সাথী',
      'auth.email': 'ইমেইল',
      'auth.password': 'পাসওয়ার্ড',
      'auth.login': 'লগইন',
      'auth.orLoginWith': 'অথবা লগইন করুন',
      'auth.dontHaveAccount': 'অ্যাকাউন্ট নেই?',
      'auth.createNewAccount': 'নতুন অ্যাকাউন্ট তৈরি করুন',
      'auth.createNewAshaAccount': 'নতুন \nআশা অ্যাকাউন্ট তৈরি করুন',
      'auth.username': 'ব্যবহারকারীর নাম',
      'auth.phoneNumber': 'ফোন নম্বর',
      'auth.create': 'তৈরি করুন',
      'auth.orSignupWith': 'অথবা সাইন আপ করুন',
      'auth.alreadyHaveAccount': 'আগে থেকেই অ্যাকাউন্ট আছে?',
      'home.settings': 'সেটিংস',
      'home.language': 'ভাষা',
      'home.welcome': 'স্বাগতম,\n',
      'home.ashaWorker': 'আশা কর্মী!',
      'home.dailyOverview': 'আপনার দৈনিক স্বাস্থ্য সারাংশ প্রস্তুত',
      'home.dailyTasks': 'দৈনিক কাজ',
      'home.recentPatients': 'সাম্প্রতিক রোগী',
      'home.noTasksToday': 'আজ কোনো কাজ নেই',
      'home.noPatientsFound': 'কোনো রোগী পাওয়া যায়নি',
      'nav.dashboard': 'ড্যাশবোর্ড',
      'nav.addPatient': 'রোগী যোগ করুন',
      'nav.phcPortal': 'পিএইচসি পোর্টাল',
      'nav.dashboardTitle': 'আশা ড্যাশবোর্ড',
      'drawer.logout': 'লগ আউট',
      'task.addNewTask': 'নতুন কাজ যোগ করুন',
      'task.createNewTask': 'নতুন কাজ তৈরি করুন',
      'task.taskTitle': 'কাজের শিরোনাম',
      'task.taskTitleHint': 'যেমন: রোগী ফলো-আপ',
      'task.taskDescription': 'কাজের বিবরণ',
      'task.taskDescriptionHint': 'কাজের বিবরণ লিখুন...',
      'task.status': 'অবস্থা',
      'task.saveTask': 'কাজ সংরক্ষণ করুন',
      'task.pleaseEnterTitle': 'কাজের শিরোনাম লিখুন',
      'task.addedSuccessfully': 'কাজ সফলভাবে যোগ হয়েছে!',
      'task.urgent': 'জরুরি',
      'task.pending': 'মুলতুবি',
      'task.inProgress': 'চলমান',
      'task.completed': 'সম্পন্ন',
      'task.done': 'সম্পন্ন',
      'task.deleteTask': 'কাজ মুছুন',
      'task.deleteTaskConfirm': 'আপনি কি এই কাজটি মুছতে চান?',
      'task.deletedSuccessfully': 'কাজ সফলভাবে মুছে গেছে',
      'task.markedDeletion': 'কাজ মুছে ফেলার জন্য চিহ্নিত (পরে সিঙ্ক হবে)',
      'task.errorDeleting': 'কাজ মুছতে সমস্যা: {error}',
      'patient.addPhoto': 'ছবি যোগ করুন',
      'patient.patientName': 'রোগীর নাম',
      'patient.age': 'বয়স',
      'patient.address': 'ঠিকানা',
      'patient.dateOfBirth': 'জন্মতারিখ',
      'patient.selectDate': 'তারিখ নির্বাচন করুন',
      'patient.gender': 'লিঙ্গ',
      'patient.female': 'মহিলা',
      'patient.male': 'পুরুষ',
      'patient.other': 'অন্যান্য',
      'patient.saveData': 'রোগীর তথ্য সংরক্ষণ করুন',
      'patient.pleaseAddPhoto': 'রোগীর ছবি যোগ করুন',
      'patient.invalidName': 'রোগীর সঠিক নাম লিখুন',
      'patient.invalidAge': '১ থেকে ১৩০ এর মধ্যে সঠিক বয়স লিখুন',
      'patient.invalidAddress': 'সম্পূর্ণ ঠিকানা লিখুন',
      'patient.invalidPhone': 'সঠিক ১০ সংখ্যার ফোন নম্বর লিখুন',
      'patient.invalidDob': 'সঠিক জন্মতারিখ নির্বাচন করুন',
      'patient.saveSuccessOnline': 'রোগীর তথ্য সফলভাবে সংরক্ষণ ও সিঙ্ক হয়েছে',
      'patient.saveSuccessOffline': 'রোগীর তথ্য অফলাইনে সংরক্ষিত হয়েছে, পরে সিঙ্ক হবে',
      'patient.saveFailed': 'রোগীর তথ্য সংরক্ষণ করা যায়নি। আবার চেষ্টা করুন।',
      'patient.takePhoto': 'ছবি তুলুন',
      'patient.chooseFromGallery': 'গ্যালারি থেকে বাছাই করুন',
      'patient.saved': 'রোগী সংরক্ষিত',
      'patient.savedDetails': 'বিস্তারিত সফলভাবে সংরক্ষিত হয়েছে',
      'patient.details': 'রোগীর বিস্তারিত',
      'patient.stepFamily': 'পরিবার',
      'patient.stepPatient': 'রোগী',
      'patient.stepMedical': 'চিকিৎসা',
      'patient.sessionExpiredLogin': 'সেশন শেষ হয়ে গেছে। অনুগ্রহ করে আবার লগইন করুন।',
      'patient.familyRegisteredSuccess': 'পরিবার সফলভাবে নিবন্ধিত হয়েছে!',
      'patient.saveFailedTryAgain': 'সংরক্ষণ করা যায়নি। অনুগ্রহ করে আবার চেষ্টা করুন।',
      'patient.familyInformation': 'পারিবারিক তথ্য',
      'patient.headOfFamilyRequired': 'পরিবারের প্রধান *',
      'patient.enterHeadOfFamily': 'পরিবারের প্রধানের নাম লিখুন *',
      'patient.numberOfMembers': 'সদস্য সংখ্যা',
      'patient.familyAddressRequired': 'পারিবারিক ঠিকানা *',
      'patient.enterFamilyAddress': 'পারিবারিক ঠিকানা লিখুন *',
      'patient.useAddressForAllFamilyMembers': 'এই ঠিকানা সব পরিবারের সদস্যের জন্য ব্যবহার করুন',
      'patient.familyInfoHelpText': 'পরিবারের প্রধানের নাম এবং মোট সদস্য সংখ্যা লিখুন। আলাদা করে উল্লেখ না করলে পরিবারের ঠিকানা সব সদস্যের জন্য ব্যবহার হবে।',
      'patient.patientNameRequired': 'রোগীর নাম *',
      'patient.caste': 'জাতি',
      'patient.memberWithIndex': 'সদস্য {index}',
      'patient.changePhoto': 'ছবি পরিবর্তন করুন',
      'patient.removePhoto': 'ছবি সরান',
      'patient.removeMemberTitle': 'সদস্য সরাবেন?',
      'patient.removeMemberPromptDefault': 'এই সদস্যকে সরাবেন?',
      'patient.removeMemberPromptNamed': '{name} কে সরাবেন?',
      'patient.remove': 'সরান',
      'patient.removeThisMember': 'এই সদস্যকে সরান',
      'patient.isPregnant': 'গর্ভবতী?',
      'patient.expectedDeliveryDate': 'সম্ভাব্য প্রসবের তারিখ',
      'patient.monthsOfPregnancy': 'গর্ভাবস্থার মাস',
      'patient.monthsCount': '{count} মাস',
      'patient.sameAsFamilyAddress': 'পারিবারিক ঠিকানার মতোই',
      'patient.patientAddress': 'রোগীর ঠিকানা',
      'patient.medicalInformation': 'চিকিৎসা তথ্য',
      'patient.privacyDeclined': 'রোগী চিকিৎসা তথ্য শেয়ার করতে চান না',
      'patient.privacyDeclinedBanner': 'রোগী চিকিৎসা তথ্য শেয়ার করতে অস্বীকার করেছেন',
      'patient.selectHealthConditions': 'স্বাস্থ্য পরিস্থিতি নির্বাচন করুন',
      'patient.additionalNotes': 'অতিরিক্ত নোট',
      'patient.additionalNotesHint': 'রোগী সম্পর্কে অতিরিক্ত নোট লিখুন...',
      'patient.summary': 'সারাংশ',
      'patient.totalPatients': 'মোট রোগী: {count}',
      'patient.conditionsSelected': 'নির্বাচিত পরিস্থিতি: {count}',
      'patient.privacyDeclinedSummary': 'গোপনীয়তা: রোগী স্বাস্থ্য তথ্য শেয়ার করতে অস্বীকার করেছেন',
      'patient.condition.bp': 'BP',
      'patient.condition.elephantiasis': 'হাতিপা',
      'patient.condition.diabetes': 'ডায়াবেটিস',
      'patient.condition.heartDisease': 'হৃদরোগ',
      'patient.condition.asthma': 'অ্যাজমা',
      'patient.condition.thyroid': 'থাইরয়েড',
      'patient.condition.arthritis': 'আর্থ্রাইটিস',
      'patient.condition.kidney': 'কিডনি',
      'patient.condition.liver': 'লিভার',
      'patient.condition.cancer': 'ক্যান্সার',
      'patient.ageYears': '{age} বছর',
      'patient.phone': 'ফোন',
      'patient.delete': 'রোগী মুছুন',
      'patient.deleteConfirm':
          'এটি রোগীর তথ্য মুছে দেবে। অফলাইনে থাকলে পরে সিঙ্ক করতে পারবেন।',
      'patient.markedDeletion':
          'রোগী মুছে ফেলার জন্য চিহ্নিত (অনলাইনে সিঙ্ক হবে)',
      'patient.deletedSuccessfully': 'রোগী সফলভাবে মুছে গেছে',
      'patient.deleteFailedStatus': 'মুছতে ব্যর্থ: {status}। পরে সিঙ্ক হবে',
      'patient.errorDeleting': 'মুছতে সমস্যা: {error}। পরে সিঙ্ক হবে',
      'patients.title': 'রোগী',
      'patients.searchHint': 'নাম বা আইডি দিয়ে খুঁজুন...',
      'patients.quickFilters': 'দ্রুত ফিল্টার',
      'patients.allGender': 'সব লিঙ্গ',
      'patients.others': 'অন্যান্য',
      'patients.age18to35': 'বয়স: ১৮-৩৫',
      'patients.recentRecords': 'সাম্প্রতিক রেকর্ড ({count})',
      'patients.showingAll': 'সব নিবন্ধিত রোগী দেখানো হচ্ছে',
      'patients.filtersHint':
          'উপরে থাকা ফিল্টার ব্যবহার করে অনুসন্ধান সীমিত করুন বা নতুন রোগীর রেকর্ড যোগ করুন।',
      'patients.newest': 'সর্বশেষ',
      'patients.oldest': 'প্রাচীনতম',
      'patients.nameAZ': 'নাম (A-Z)',
      'patients.sortBy': 'সাজান: {sort}',
      'patients.yearsShort': '{age} বছর',
      'phc.keyMetrics': 'মূল পরিমাপ',
      'phc.totalPatients': 'মোট রোগী',
      'phc.genderDistribution': 'লিঙ্গ বণ্টন',
    },
    'te': {
      'app.name': 'ఆశాసాథి',
      'common.cancel': 'రద్దు',
      'common.confirm': 'నిర్ధారించండి',
      'common.confirmSelection': 'ఎంపికను నిర్ధారించండి',
      'common.delete': 'తొలగించు',
      'common.clear': 'తొలగించు',
      'common.view': 'చూడండి',
      'common.viewAll': 'అన్నీ చూడండి',
      'common.settings': 'సెట్టింగ్స్',
      'common.language': 'భాష',
      'common.selectLanguage': 'భాషను ఎంచుకోండి',
      'common.required': 'తప్పనిసరి',
      'common.languageHint':
          'మీ అనుభవాన్ని అనుకూలీకరించేందుకు భాషను ఎంచుకోండి.',
      'theme.switchToLight': 'లైట్ మోడ్‌కు మార్చండి',
      'theme.switchToDark': 'డార్క్ మోడ్‌కు మార్చండి',
      'auth.welcomeBack': 'తిరిగి వచ్చినందుకు స్వాగతం \nఆశా సాథి',
      'auth.email': 'ఇమెయిల్',
      'auth.password': 'పాస్‌వర్డ్',
      'auth.login': 'లాగిన్',
      'auth.orLoginWith': 'లేదా దీనితో లాగిన్ అవ్వండి',
      'auth.dontHaveAccount': 'ఖాతా లేదా?',
      'auth.createNewAccount': 'కొత్త ఖాతా సృష్టించండి',
      'auth.createNewAshaAccount': 'కొత్త \nఆశా ఖాతా సృష్టించండి',
      'auth.username': 'వాడుకరి పేరు',
      'auth.phoneNumber': 'ఫోన్ నంబర్',
      'auth.create': 'సృష్టించండి',
      'auth.orSignupWith': 'లేదా దీనితో సైన్ అప్ అవ్వండి',
      'auth.alreadyHaveAccount': 'ఇప్పటికే ఖాతా ఉందా?',
      'home.settings': 'సెట్టింగ్స్',
      'home.language': 'భాష',
      'home.welcome': 'స్వాగతం,\n',
      'home.ashaWorker': 'ఆశా వర్కర్!',
      'home.dailyOverview': 'మీ రోజువారీ ఆరోగ్య సమాచారం సిద్ధంగా ఉంది',
      'home.dailyTasks': 'రోజువారీ పనులు',
      'home.recentPatients': 'ఇటీవలి రోగులు',
      'home.noTasksToday': 'ఈరోజు పనులు లేవు',
      'home.noPatientsFound': 'రోగులు కనబడలేదు',
      'nav.dashboard': 'డాష్‌బోర్డ్',
      'nav.addPatient': 'రోగిని జోడించండి',
      'nav.phcPortal': 'పీహెచ్‌సీ పోర్టల్',
      'nav.dashboardTitle': 'ఆశా డాష్‌బోర్డ్',
      'drawer.logout': 'లాగౌట్',
      'task.addNewTask': 'కొత్త పని జోడించండి',
      'task.createNewTask': 'కొత్త పని సృష్టించండి',
      'task.taskTitle': 'పని శీర్షిక',
      'task.taskTitleHint': 'ఉదా: రోగి ఫాలో-అప్',
      'task.taskDescription': 'పని వివరణ',
      'task.taskDescriptionHint': 'పని వివరాన్ని వ్రాయండి...',
      'task.status': 'స్థితి',
      'task.saveTask': 'పని సేవ్ చేయండి',
      'task.pleaseEnterTitle': 'పని శీర్షికను నమోదు చేయండి',
      'task.addedSuccessfully': 'పని విజయవంతంగా జోడించబడింది!',
      'task.urgent': 'అత్యవసరం',
      'task.pending': 'పెండింగ్',
      'task.inProgress': 'ప్రగతిలో',
      'task.completed': 'పూర్తైంది',
      'task.done': 'పూర్తైంది',
      'task.deleteTask': 'పనిని తొలగించు',
      'task.deleteTaskConfirm': 'ఈ పనిని తొలగించాలనుకుంటున్నారా?',
      'task.deletedSuccessfully': 'పని విజయవంతంగా తొలగించబడింది',
      'task.markedDeletion':
          'పని తొలగింపుగా గుర్తించబడింది (తర్వాత సమకాలీకరణ జరుగుతుంది)',
      'task.errorDeleting': 'పనిని తొలగించడంలో లోపం: {error}',
      'patient.addPhoto': 'ఫోటో జోడించండి',
      'patient.patientName': 'రోగి పేరు',
      'patient.age': 'వయస్సు',
      'patient.address': 'చిరునామా',
      'patient.dateOfBirth': 'జనన తేది',
      'patient.selectDate': 'తేదీ ఎంచుకోండి',
      'patient.gender': 'లింగం',
      'patient.female': 'స్త్రీ',
      'patient.male': 'పురుషుడు',
      'patient.other': 'ఇతర',
      'patient.saveData': 'రోగి డేటా సేవ్ చేయండి',
      'patient.pleaseAddPhoto': 'దయచేసి రోగి ఫోటో జోడించండి',
      'patient.invalidName': 'దయచేసి సరైన రోగి పేరు నమోదు చేయండి',
      'patient.invalidAge': 'దయచేసి 1 నుండి 130 మధ్య సరైన వయస్సు నమోదు చేయండి',
      'patient.invalidAddress': 'దయచేసి పూర్తి చిరునామా నమోదు చేయండి',
      'patient.invalidPhone': 'దయచేసి సరైన 10 అంకెల ఫోన్ నంబర్ నమోదు చేయండి',
      'patient.invalidDob': 'దయచేసి సరైన జనన తేది ఎంచుకోండి',
      'patient.saveSuccessOnline': 'రోగి వివరాలు విజయవంతంగా సేవ్ చేసి సమకాలీకరించబడ్డాయి',
      'patient.saveSuccessOffline': 'రోగి వివరాలు ఆఫ్‌లైన్‌లో సేవ్ అయ్యాయి, తర్వాత సమకాలీకరిస్తాం',
      'patient.saveFailed': 'రోగి వివరాలు సేవ్ కాలేదు. దయచేసి మళ్లీ ప్రయత్నించండి.',
      'patient.takePhoto': 'ఫోటో తీయండి',
      'patient.chooseFromGallery': 'గ్యాలరీ నుండి ఎంచుకోండి',
      'patient.saved': 'రోగి సేవ్ చేయబడింది',
      'patient.savedDetails': 'వివరాలు విజయవంతంగా నమోదు అయ్యాయి',
      'patient.details': 'రోగి వివరాలు',
      'patient.ageYears': '{age} సంవత్సరాలు',
      'patient.phone': 'ఫోన్',
      'patient.delete': 'రోగిని తొలగించు',
      'patient.deleteConfirm':
          'ఇది రోగిని తొలగిస్తుంది. ఆఫ్లైన్‌లో ఉంటే తర్వాత సమకాలీకరించవచ్చు.',
      'patient.markedDeletion':
          'రోగి తొలగింపుగా గుర్తించబడింది (ఆన్‌లైన్‌లో సమకాలీకరించబడుతుంది)',
      'patient.deletedSuccessfully': 'రోగి విజయవంతంగా తొలగించబడింది',
      'patient.deleteFailedStatus':
          'తొలగించడం విఫలమైంది: {status}. తర్వాత సమకాలీకరణ అవుతుంది',
        'patient.stepFamily': 'కుటుంబం',
        'patient.stepPatient': 'రోగి',
        'patient.stepMedical': 'వైద్యం',
        'patient.sessionExpiredLogin': 'సెషన్ ముగిసింది. దయచేసి మళ్లీ లాగిన్ చేయండి.',
        'patient.familyRegisteredSuccess': 'కుటుంబం విజయవంతంగా నమోదు చేయబడింది!',
        'patient.saveFailedTryAgain': 'సేవ్ చేయలేకపోయాం. దయచేసి మళ్లీ ప్రయత్నించండి.',
        'patient.familyInformation': 'కుటుంబ సమాచారం',
        'patient.headOfFamilyRequired': 'కుటుంబ ప్రధానుడు *',
        'patient.enterHeadOfFamily': 'కుటుంబ ప్రధానుడి పేరు నమోదు చేయండి *',
        'patient.numberOfMembers': 'సభ్యుల సంఖ్య',
        'patient.familyAddressRequired': 'కుటుంబ చిరునామా *',
        'patient.enterFamilyAddress': 'కుటుంబ చిరునామా నమోదు చేయండి *',
        'patient.useAddressForAllFamilyMembers': 'ఈ చిరునామాను అన్ని కుటుంబ సభ్యుల కోసం ఉపయోగించండి',
        'patient.familyInfoHelpText': 'కుటుంబ ప్రధానుడి పేరు మరియు మొత్తం సభ్యుల సంఖ్య నమోదు చేయండి. వేరేలా పేర్కొనకపోతే కుటుంబ చిరునామా అందరి కోసం ఉపయోగించబడుతుంది.',
        'patient.patientNameRequired': 'రోగి పేరు *',
        'patient.caste': 'కులం',
        'patient.memberWithIndex': 'సభ్యుడు {index}',
        'patient.changePhoto': 'ఫోటో మార్చండి',
        'patient.removePhoto': 'ఫోటో తొలగించండి',
        'patient.removeMemberTitle': 'సభ్యుడిని తొలగించాలా?',
        'patient.removeMemberPromptDefault': 'ఈ సభ్యుడిని తొలగించాలా?',
        'patient.removeMemberPromptNamed': '{name} ను తొలగించాలా?',
        'patient.remove': 'తొలగించండి',
        'patient.removeThisMember': 'ఈ సభ్యుడిని తొలగించండి',
        'patient.isPregnant': 'గర్భవతినా?',
        'patient.expectedDeliveryDate': 'అంచనా ప్రసవ తేదీ',
        'patient.monthsOfPregnancy': 'గర్భధారణ నెలలు',
        'patient.monthsCount': '{count} నెలలు',
        'patient.sameAsFamilyAddress': 'కుటుంబ చిరునామాతో సమానం',
        'patient.patientAddress': 'రోగి చిరునామా',
        'patient.medicalInformation': 'వైద్య సమాచారం',
        'patient.privacyDeclined': 'రోగి వైద్య సమాచారం పంచుకోవడం ఇష్టపడలేదు',
        'patient.privacyDeclinedBanner': 'రోగి వైద్య సమాచారాన్ని పంచుకోవడానికి నిరాకరించారు',
        'patient.selectHealthConditions': 'ఆరోగ్య పరిస్థితులను ఎంచుకోండి',
        'patient.additionalNotes': 'అదనపు గమనికలు',
        'patient.additionalNotesHint': 'రోగి గురించి అదనపు గమనికలు జోడించండి...',
        'patient.summary': 'సారాంశం',
        'patient.totalPatients': 'మొత్తం రోగులు: {count}',
        'patient.conditionsSelected': 'ఎంపిక చేసిన పరిస్థితులు: {count}',
        'patient.privacyDeclinedSummary': 'గోప్యత: రోగి ఆరోగ్య సమాచారాన్ని పంచుకోవడానికి నిరాకరించారు',
        'patient.condition.bp': 'BP',
        'patient.condition.elephantiasis': 'ఎలిఫాంటియాసిస్',
        'patient.condition.diabetes': 'షుగర్',
        'patient.condition.heartDisease': 'హృదయ వ్యాధి',
        'patient.condition.asthma': 'ఆస్త్మా',
        'patient.condition.thyroid': 'థైరాయిడ్',
        'patient.condition.arthritis': 'ఆర్థరైటిస్',
        'patient.condition.kidney': 'కిడ్ని',
        'patient.condition.liver': 'లివర్',
        'patient.condition.cancer': 'క్యాన్సర్',
      'patients.title': 'రోగులు',
      'patients.searchHint': 'పేరు లేదా ఐడీ ద్వారా వెతకండి...',
      'patients.quickFilters': 'తక్షణ ఫిల్టర్లు',
      'patients.allGender': 'అన్ని లింగాలు',
      'patients.others': 'ఇతరులు',
      'patients.age18to35': 'వయస్సు: 18-35',
      'patients.recentRecords': 'ఇటీవలి రికార్డులు ({count})',
      'patients.showingAll': 'అన్ని నమోదు చేసిన రోగులు చూపబడుతున్నారు',
      'patients.filtersHint':
          'మీ శోధనను మెరుగుపరచడానికి పై ఫిల్టర్లు ఉపయోగించండి లేదా కొత్త రోగి రికార్డు జోడించండి.',
      'patients.newest': 'కొత్తవి',
      'patients.oldest': 'పాతవి',
      'patients.nameAZ': 'పేరు (A-Z)',
      'patients.sortBy': 'క్రమబద్ధీకరణ: {sort}',
      'patients.yearsShort': '{age} సం.',
      'phc.keyMetrics': 'ముఖ్య సూచికలు',
      'phc.totalPatients': 'మొత్తం రోగులు',
      'phc.genderDistribution': 'లింగ విభజన',
    },
    'mr': {
      'app.name': 'आशासाथी',
      'common.cancel': 'रद्द करा',
      'common.back': 'मागे',
      'common.next': 'पुढे',
      'common.confirm': 'पुष्टी करा',
      'common.errorWithMessage': 'त्रुटी: {error}',
      'common.confirmSelection': 'निवड पुष्टी करा',
      'common.delete': 'हटवा',
      'common.clear': 'साफ करा',
      'common.view': 'पहा',
      'common.viewAll': 'सर्व पहा',
      'common.settings': 'सेटिंग्ज',
      'common.language': 'भाषा',
      'common.selectLanguage': 'भाषा निवडा',
      'common.required': 'आवश्यक',
      'common.languageHint': 'अनुभव सानुकूल करण्यासाठी पसंतीची भाषा निवडा.',
      'theme.switchToLight': 'लाईट मोडवर जा',
      'theme.switchToDark': 'डार्क मोडवर जा',
      'auth.welcomeBack': 'पुन्हा स्वागत आहे \nआशा साथी',
      'auth.email': 'ईमेल',
      'auth.password': 'पासवर्ड',
      'auth.login': 'लॉगिन',
      'auth.orLoginWith': 'किंवा याने लॉगिन करा',
      'auth.dontHaveAccount': 'खाते नाही का?',
      'auth.createNewAccount': 'नवे खाते तयार करा',
      'auth.createNewAshaAccount': 'नवे \nआशा खाते तयार करा',
      'auth.username': 'वापरकर्ता नाव',
      'auth.phoneNumber': 'फोन नंबर',
      'auth.create': 'तयार करा',
      'auth.orSignupWith': 'किंवा याने साइन अप करा',
      'auth.alreadyHaveAccount': 'आधीच खाते आहे का?',
      'home.settings': 'सेटिंग्ज',
      'home.language': 'भाषा',
      'home.welcome': 'स्वागत आहे,\n',
      'home.ashaWorker': 'आशा कार्यकर्ता!',
      'home.dailyOverview': 'तुमचा रोजचा आरोग्य आढावा तयार आहे',
      'home.dailyTasks': 'दैनंदिन कामे',
      'home.recentPatients': 'अलीकडील रुग्ण',
      'home.noTasksToday': 'आज कोणतीही कामे नाहीत',
      'home.noPatientsFound': 'रुग्ण सापडले नाहीत',
      'nav.dashboard': 'डॅशबोर्ड',
      'nav.addPatient': 'रुग्ण जोडा',
      'nav.phcPortal': 'पीएचसी पोर्टल',
      'nav.dashboardTitle': 'आशा डॅशबोर्ड',
      'drawer.logout': 'लॉग आउट',
      'task.addNewTask': 'नवीन काम जोडा',
      'task.createNewTask': 'नवीन काम तयार करा',
      'task.taskTitle': 'कामाचे शीर्षक',
      'task.taskTitleHint': 'उदा., रुग्ण फॉलो-अप',
      'task.taskDescription': 'कामाचे वर्णन',
      'task.taskDescriptionHint': 'कामाचे वर्णन लिहा...',
      'task.status': 'स्थिती',
      'task.saveTask': 'काम सेव्ह करा',
      'task.pleaseEnterTitle': 'कामाचे शीर्षक भरा',
      'task.addedSuccessfully': 'काम यशस्वीपणे जोडले गेले!',
      'task.urgent': 'तातडीचे',
      'task.pending': 'प्रलंबित',
      'task.inProgress': 'सुरू आहे',
      'task.completed': 'पूर्ण',
      'task.done': 'पूर्ण',
      'task.deleteTask': 'काम हटवा',
      'task.deleteTaskConfirm': 'हे काम हटवायचे आहे का?',
      'task.deletedSuccessfully': 'काम यशस्वीपणे हटवले',
      'task.markedDeletion': 'काम हटवण्यासाठी चिन्हांकित केले (नंतर सिंक होईल)',
      'task.errorDeleting': 'काम हटवताना त्रुटी: {error}',
      'patient.addPhoto': 'फोटो जोडा',
      'patient.patientName': 'रुग्णाचे नाव',
      'patient.age': 'वय',
      'patient.address': 'पत्ता',
      'patient.dateOfBirth': 'जन्मतारीख',
      'patient.selectDate': 'तारीख निवडा',
      'patient.gender': 'लिंग',
      'patient.female': 'स्त्री',
      'patient.male': 'पुरुष',
      'patient.other': 'इतर',
      'patient.saveData': 'रुग्णाची माहिती सेव्ह करा',
      'patient.pleaseAddPhoto': 'कृपया रुग्णाचा फोटो जोडा',
      'patient.invalidName': 'कृपया रुग्णाचे योग्य नाव भरा',
      'patient.invalidAge': 'कृपया 1 ते 130 दरम्यान योग्य वय भरा',
      'patient.invalidAddress': 'कृपया पूर्ण पत्ता भरा',
      'patient.invalidPhone': 'कृपया वैध 10 अंकी फोन नंबर भरा',
      'patient.invalidDob': 'कृपया योग्य जन्मतारीख निवडा',
      'patient.saveSuccessOnline': 'रुग्णाची माहिती यशस्वीपणे सेव्ह आणि सिंक झाली',
      'patient.saveSuccessOffline': 'रुग्णाची माहिती ऑफलाइन सेव्ह झाली, नंतर सिंक होईल',
      'patient.saveFailed': 'रुग्णाची माहिती सेव्ह करता आली नाही. कृपया पुन्हा प्रयत्न करा.',
      'patient.takePhoto': 'फोटो काढा',
      'patient.chooseFromGallery': 'गॅलरीमधून निवडा',
      'patient.saved': 'रुग्ण सेव्ह झाला',
      'patient.savedDetails': 'तपशील यशस्वीपणे नोंदवले गेले',
      'patient.details': 'रुग्ण तपशील',
      'patient.ageYears': '{age} वर्षे',
      'patient.phone': 'फोन',
      'patient.delete': 'रुग्ण हटवा',
      'patient.deleteConfirm':
          'यामुळे रुग्ण हटवला जाईल. ऑफलाइन असल्यास नंतर सिंक करू शकता.',
      'patient.markedDeletion':
          'रुग्ण हटवण्यासाठी चिन्हांकित (ऑनलाइन झाल्यावर सिंक होईल)',
      'patient.deletedSuccessfully': 'रुग्ण यशस्वीपणे हटवला गेला',
      'patient.deleteFailedStatus': 'हटवणे अयशस्वी: {status}. नंतर सिंक होईल',
      'patient.errorDeleting': 'हटवताना त्रुटी: {error}. नंतर सिंक होईल',
      'patients.title': 'रुग्ण',
      'patients.searchHint': 'नाव किंवा आयडीने शोधा...',
      'patients.quickFilters': 'त्वरित फिल्टर्स',
      'patients.allGender': 'सर्व लिंग',
      'patients.others': 'इतर',
      'patients.age18to35': 'वय: 18-35',
      'patients.recentRecords': 'अलीकडील नोंदी ({count})',
      'patients.showingAll': 'सर्व नोंदणीकृत रुग्ण दाखवले जात आहेत',
      'patients.filtersHint':
          'शोध अधिक अचूक करण्यासाठी वरील फिल्टर्स वापरा किंवा नवीन रुग्ण नोंद जोडा.',
      'patients.newest': 'नवीन',
      'patients.oldest': 'जुने',
      'patients.nameAZ': 'नाव (A-Z)',
      'patients.sortBy': 'क्रम लावा: {sort}',
      'patients.yearsShort': '{age} वर्षे',
      'phc.keyMetrics': 'मुख्य मेट्रिक्स',
      'phc.totalPatients': 'एकूण रुग्ण',
      'phc.genderDistribution': 'लिंग वितरण',
    },
    'ta': {
      'app.name': 'ஆஷா சாத்தி',
      'common.cancel': 'ரத்து',
      'common.back': 'பின்செல்',
      'common.next': 'அடுத்து',
      'common.confirm': 'உறுதிப்படுத்து',
      'common.errorWithMessage': 'பிழை: {error}',
      'common.confirmSelection': 'தேர்வை உறுதிப்படுத்து',
      'common.delete': 'நீக்கு',
      'common.clear': 'அழி',
      'common.view': 'பார்',
      'common.viewAll': 'அனைத்தையும் பார்',
      'common.settings': 'அமைப்புகள்',
      'common.language': 'மொழி',
      'common.selectLanguage': 'மொழியைத் தேர்வு செய்க',
      'common.required': 'தேவையானது',
      'common.languageHint':
          'உங்கள் அனுபவத்தை தனிப்பயனாக்க மொழியை தேர்வு செய்யவும்.',
      'theme.switchToLight': 'ஒளி நிலைக்கு மாற்று',
      'theme.switchToDark': 'இருள் நிலைக்கு மாற்று',
      'auth.welcomeBack': 'மீண்டும் வரவேற்கிறோம் \nஆஷா சாத்தி',
      'auth.email': 'மின்னஞ்சல்',
      'auth.password': 'கடவுச்சொல்',
      'auth.login': 'உள்நுழை',
      'auth.orLoginWith': 'அல்லது இதன் மூலம் உள்நுழைக',
      'auth.dontHaveAccount': 'கணக்கு இல்லையா?',
      'auth.createNewAccount': 'புதிய கணக்கு உருவாக்கவும்',
      'auth.createNewAshaAccount': 'புதிய \nஆஷா கணக்கு உருவாக்கவும்',
      'auth.username': 'பயனர் பெயர்',
      'auth.phoneNumber': 'தொலைபேசி எண்',
      'auth.create': 'உருவாக்கு',
      'auth.orSignupWith': 'அல்லது இதன் மூலம் பதிவு செய்யவும்',
      'auth.alreadyHaveAccount': 'ஏற்கனவே கணக்கு உள்ளதா?',
      'home.settings': 'அமைப்புகள்',
      'home.language': 'மொழி',
      'home.welcome': 'வரவேற்கிறோம்,\n',
      'home.ashaWorker': 'ஆஷா பணியாளர்!',
      'home.dailyOverview': 'உங்கள் தினசரி சுகாதார கண்ணோட்டம் தயாராக உள்ளது',
      'home.dailyTasks': 'தினசரி பணிகள்',
      'home.recentPatients': 'சமீபத்திய நோயாளிகள்',
      'home.noTasksToday': 'இன்றைக்கு பணிகள் இல்லை',
      'home.noPatientsFound': 'நோயாளிகள் எதுவும் கிடைக்கவில்லை',
      'nav.dashboard': 'டாஷ்போர்டு',
      'nav.addPatient': 'நோயாளியைச் சேர்க்கவும்',
      'nav.phcPortal': 'பிஎச்ச்சி போர்டல்',
      'nav.dashboardTitle': 'ஆஷா டாஷ்போர்டு',
      'drawer.logout': 'வெளியேறு',
      'task.addNewTask': 'புதிய பணியைச் சேர்',
      'task.createNewTask': 'புதிய பணியை உருவாக்கு',
      'task.taskTitle': 'பணி தலைப்பு',
      'task.taskTitleHint': 'எ.கா., நோயாளி பின்தொடர்பு',
      'task.taskDescription': 'பணி விளக்கம்',
      'task.taskDescriptionHint': 'பணியை விவரிக்கவும்...',
      'task.status': 'நிலை',
      'task.saveTask': 'பணியை சேமி',
      'task.pleaseEnterTitle': 'பணி தலைப்பை உள்ளிடவும்',
      'task.addedSuccessfully': 'பணி வெற்றிகரமாக சேர்க்கப்பட்டது!',
      'task.urgent': 'அவசரம்',
      'task.pending': 'நிலுவையில்',
      'task.inProgress': 'நடைபெறுகிறது',
      'task.completed': 'முடிந்தது',
      'task.done': 'முடிந்தது',
      'task.deleteTask': 'பணியை நீக்கு',
      'task.deleteTaskConfirm': 'இந்த பணியை நீக்க விரும்புகிறீர்களா?',
      'task.deletedSuccessfully': 'பணி வெற்றிகரமாக நீக்கப்பட்டது',
      'task.markedDeletion':
          'பணி நீக்கத்திற்காக குறிக்கப்பட்டது (பின்னர் ஒத்திசைக்கப்படும்)',
      'task.errorDeleting': 'பணியை நீக்குவதில் பிழை: {error}',
      'patient.addPhoto': 'புகைப்படம் சேர்க்கவும்',
      'patient.patientName': 'நோயாளியின் பெயர்',
      'patient.age': 'வயது',
      'patient.address': 'முகவரி',
      'patient.dateOfBirth': 'பிறந்த தேதி',
      'patient.selectDate': 'தேதியைத் தேர்வு செய்க',
      'patient.gender': 'பாலினம்',
      'patient.female': 'பெண்',
      'patient.male': 'ஆண்',
      'patient.other': 'மற்றவை',
      'patient.saveData': 'நோயாளி தரவை சேமிக்கவும்',
      'patient.pleaseAddPhoto': 'தயவுசெய்து நோயாளி புகைப்படத்தைச் சேர்க்கவும்',
      'patient.invalidName': 'சரியான நோயாளி பெயரை உள்ளிடவும்',
      'patient.invalidAge': '1 முதல் 130 வரை சரியான வயதை உள்ளிடவும்',
      'patient.invalidAddress': 'முழுமையான முகவரியை உள்ளிடவும்',
      'patient.invalidPhone': 'சரியான 10 இலக்க தொலைபேசி எண்ணை உள்ளிடவும்',
      'patient.invalidDob': 'சரியான பிறந்த தேதியைத் தேர்ந்தெடுக்கவும்',
      'patient.saveSuccessOnline': 'நோயாளி தகவல் வெற்றிகரமாக சேமித்து ஒத்திசைக்கப்பட்டது',
      'patient.saveSuccessOffline': 'நோயாளி தகவல் ஆஃப்லைனில் சேமிக்கப்பட்டது, பின்னர் ஒத்திசைக்கப்படும்',
      'patient.saveFailed': 'நோயாளி தகவலை சேமிக்க முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
      'patient.takePhoto': 'புகைப்படம் எடுக்கவும்',
      'patient.chooseFromGallery': 'கேலரியில் இருந்து தேர்வு செய்க',
      'patient.saved': 'நோயாளி சேமிக்கப்பட்டார்',
      'patient.savedDetails': 'விவரங்கள் வெற்றிகரமாக பதிவு செய்யப்பட்டது',
      'patient.details': 'நோயாளி விவரங்கள்',
      'patient.stepFamily': 'குடும்பம்',
      'patient.stepPatient': 'நோயாளி',
      'patient.stepMedical': 'மருத்துவம்',
      'patient.sessionExpiredLogin': 'அமர்வு முடிந்துவிட்டது. மீண்டும் உள்நுழைக.',
      'patient.familyRegisteredSuccess': 'குடும்பம் வெற்றிகரமாக பதிவு செய்யப்பட்டது!',
      'patient.saveFailedTryAgain': 'சேமிக்க முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
      'patient.familyInformation': 'குடும்பத் தகவல்',
      'patient.headOfFamilyRequired': 'குடும்பத் தலைவர் *',
      'patient.enterHeadOfFamily': 'குடும்பத் தலைவரின் பெயரை உள்ளிடவும் *',
      'patient.numberOfMembers': 'உறுப்பினர்களின் எண்ணிக்கை',
      'patient.familyAddressRequired': 'குடும்ப முகவரி *',
      'patient.enterFamilyAddress': 'குடும்ப முகவரியை உள்ளிடவும் *',
      'patient.useAddressForAllFamilyMembers': 'இந்த முகவரியை அனைத்து குடும்ப உறுப்பினர்களுக்கும் பயன்படுத்தவும்',
      'patient.familyInfoHelpText': 'குடும்பத் தலைவரின் பெயரும் மொத்த உறுப்பினர்களின் எண்ணிக்கையும் உள்ளிடவும். வேறு விதமாக குறிப்பிடப்படாவிட்டால் குடும்ப முகவரி அனைவருக்கும் பயன்படுத்தப்படும்.',
      'patient.patientNameRequired': 'நோயாளி பெயர் *',
      'patient.caste': 'சாதி',
      'patient.memberWithIndex': 'உறுப்பினர் {index}',
      'patient.changePhoto': 'புகைப்படத்தை மாற்றவும்',
      'patient.removePhoto': 'புகைப்படத்தை அகற்று',
      'patient.removeMemberTitle': 'உறுப்பினரை அகற்றவா?',
      'patient.removeMemberPromptDefault': 'இந்த உறுப்பினரை அகற்றவா?',
      'patient.removeMemberPromptNamed': '{name} ஐ அகற்றவா?',
      'patient.remove': 'அகற்று',
      'patient.removeThisMember': 'இந்த உறுப்பினரை அகற்று',
      'patient.isPregnant': 'கர்ப்பமாக உள்ளாரா?',
      'patient.expectedDeliveryDate': 'எதிர்பார்க்கப்படும் பிரசவ தேதி',
      'patient.monthsOfPregnancy': 'கர்ப்பத்தின் மாதங்கள்',
      'patient.monthsCount': '{count} மாதம்',
      'patient.sameAsFamilyAddress': 'குடும்ப முகவரியைப் போலவே',
      'patient.patientAddress': 'நோயாளி முகவரி',
      'patient.medicalInformation': 'மருத்துவ தகவல்',
      'patient.privacyDeclined': 'நோயாளி மருத்துவ தகவலை பகிர விரும்பவில்லை',
      'patient.privacyDeclinedBanner': 'நோயாளி மருத்துவ தகவலை பகிர மறுத்துள்ளார்',
      'patient.selectHealthConditions': 'சுகாதார நிலைகளைத் தேர்ந்தெடுக்கவும்',
      'patient.additionalNotes': 'கூடுதல் குறிப்புகள்',
      'patient.additionalNotesHint': 'நோயாளியைப் பற்றிய கூடுதல் குறிப்புகளைச் சேர்க்கவும்...',
      'patient.summary': 'சுருக்கம்',
      'patient.totalPatients': 'மொத்த நோயாளிகள்: {count}',
      'patient.conditionsSelected': 'தேர்ந்தெடுக்கப்பட்ட நிலைகள்: {count}',
      'patient.privacyDeclinedSummary': 'தனியுரிமை: நோயாளி சுகாதார தகவலை பகிர மறுத்துள்ளார்',
      'patient.condition.bp': 'BP',
      'patient.condition.elephantiasis': 'யானைக்கால் நோய்',
      'patient.condition.diabetes': 'சர்க்கரை நோய்',
      'patient.condition.heartDisease': 'இதய நோய்',
      'patient.condition.asthma': 'ஆஸ்துமா',
      'patient.condition.thyroid': 'தைராய்டு',
      'patient.condition.arthritis': 'மூட்டு வலி',
      'patient.condition.kidney': 'சிறுநீரகம்',
      'patient.condition.liver': 'கல்லீரல்',
      'patient.condition.cancer': 'புற்றுநோய்',
      'patient.ageYears': '{age} ஆண்டுகள்',
      'patient.phone': 'தொலைபேசி',
      'patient.delete': 'நோயாளியை நீக்கு',
      'patient.deleteConfirm':
          'இது நோயாளியை நீக்கும். ஆஃப்லைனில் இருந்தால் பின்னர் ஒத்திசைக்கலாம்.',
      'patient.markedDeletion':
          'நோயாளி நீக்கத்திற்காக குறிக்கப்பட்டார் (ஆன்லைனில் ஒத்திசைக்கப்படும்)',
      'patient.deletedSuccessfully': 'நோயாளி வெற்றிகரமாக நீக்கப்பட்டார்',
      'patient.deleteFailedStatus':
          'நீக்குதல் தோல்வி: {status}. பின்னர் ஒத்திசைக்கும்',
      'patient.errorDeleting':
          'நீக்குவதில் பிழை: {error}. பின்னர் ஒத்திசைக்கும்',
      'patients.title': 'நோயாளிகள்',
      'patients.searchHint': 'பெயர் அல்லது ஐடி மூலம் தேடுங்கள்...',
      'patients.quickFilters': 'விரைவு வடிகட்டிகள்',
      'patients.allGender': 'அனைத்து பாலினங்கள்',
      'patients.others': 'மற்றவர்கள்',
      'patients.age18to35': 'வயது: 18-35',
      'patients.recentRecords': 'சமீபத்திய பதிவுகள் ({count})',
      'patients.showingAll':
          'அனைத்து பதிவு செய்யப்பட்ட நோயாளிகளும் காட்டப்படுகின்றனர்',
      'patients.filtersHint':
          'தேடலை துல்லியப்படுத்த மேலுள்ள வடிகட்டிகளைப் பயன்படுத்தவும் அல்லது புதிய நோயாளி பதிவைச் சேர்க்கவும்.',
      'patients.newest': 'புதியவை',
      'patients.oldest': 'பழையவை',
      'patients.nameAZ': 'பெயர் (A-Z)',
      'patients.sortBy': 'வரிசைப்படுத்து: {sort}',
      'patients.yearsShort': '{age} வயது',
      'phc.keyMetrics': 'முக்கிய அளவுகோல்கள்',
      'phc.totalPatients': 'மொத்த நோயாளிகள்',
      'phc.genderDistribution': 'பாலினப் பகிர்வு',
    },
    'gu': {
      'app.name': 'આશાસાથી',
      'common.cancel': 'રદ કરો',
      'common.back': 'પાછળ',
      'common.next': 'આગળ',
      'common.confirm': 'પુષ્ટિ કરો',
      'common.errorWithMessage': 'ભૂલ: {error}',
      'common.confirmSelection': 'પસંદગીની પુષ્ટિ કરો',
      'common.delete': 'કાઢી નાખો',
      'common.clear': 'સાફ કરો',
      'common.view': 'જુઓ',
      'common.viewAll': 'બધું જુઓ',
      'common.settings': 'સેટિંગ્સ',
      'common.language': 'ભાષા',
      'common.selectLanguage': 'ભાષા પસંદ કરો',
      'common.required': 'જરૂરી',
      'common.languageHint': 'તમારો અનુભવ અનુકૂળ કરવા પસંદગીની ભાષા પસંદ કરો.',
      'theme.switchToLight': 'લાઇટ મોડ પર સ્વિચ કરો',
      'theme.switchToDark': 'ડાર્ક મોડ પર સ્વિચ કરો',
      'auth.welcomeBack': 'ફરી સ્વાગત છે \nઆશા સાથી',
      'auth.email': 'ઈમેઈલ',
      'auth.password': 'પાસવર્ડ',
      'auth.login': 'લૉગિન',
      'auth.orLoginWith': 'અથવા આથી લૉગિન કરો',
      'auth.dontHaveAccount': 'એકાઉન્ટ નથી?',
      'auth.createNewAccount': 'નવું એકાઉન્ટ બનાવો',
      'auth.createNewAshaAccount': 'નવું \nઆશા એકાઉન્ટ બનાવો',
      'auth.username': 'વપરાશકર્તા નામ',
      'auth.phoneNumber': 'ફોન નંબર',
      'auth.create': 'બનાવો',
      'auth.orSignupWith': 'અથવા આથી સાઇન અપ કરો',
      'auth.alreadyHaveAccount': 'પહેલેથી એકાઉન્ટ છે?',
      'home.settings': 'સેટિંગ્સ',
      'home.language': 'ભાષા',
      'home.welcome': 'સ્વાગત છે,\n',
      'home.ashaWorker': 'આશા કાર્યકર!',
      'home.dailyOverview': 'તમારો દૈનિક આરોગ્ય સારાંશ તૈયાર છે',
      'home.dailyTasks': 'દૈનિક કાર્યો',
      'home.recentPatients': 'તાજેતરના દર્દીઓ',
      'home.noTasksToday': 'આજે કોઈ કાર્ય નથી',
      'home.noPatientsFound': 'કોઈ દર્દી મળ્યા નથી',
      'nav.dashboard': 'ડેશબોર્ડ',
      'nav.addPatient': 'દર્દી ઉમેરો',
      'nav.phcPortal': 'પીએચસી પોર્ટલ',
      'nav.dashboardTitle': 'આશા ડેશબોર્ડ',
      'drawer.logout': 'લૉગઆઉટ',
      'task.addNewTask': 'નવું કાર્ય ઉમેરો',
      'task.createNewTask': 'નવું કાર્ય બનાવો',
      'task.taskTitle': 'કાર્ય શીર્ષક',
      'task.taskTitleHint': 'ઉદા., દર્દી અનુસરણ',
      'task.taskDescription': 'કાર્ય વર્ણન',
      'task.taskDescriptionHint': 'કાર્યનું વર્ણન લખો...',
      'task.status': 'સ્થિતિ',
      'task.saveTask': 'કાર્ય સાચવો',
      'task.pleaseEnterTitle': 'કાર્યનું શીર્ષક દાખલ કરો',
      'task.addedSuccessfully': 'કાર્ય સફળતાપૂર્વક ઉમેરાયું!',
      'task.urgent': 'તાત્કાલિક',
      'task.pending': 'બાકી',
      'task.inProgress': 'પ્રગતિમાં',
      'task.completed': 'પૂર્ણ',
      'task.done': 'પૂર્ણ',
      'task.deleteTask': 'કાર્ય કાઢી નાખો',
      'task.deleteTaskConfirm': 'શું તમે આ કાર્ય કાઢી નાખવા માંગો છો?',
      'task.deletedSuccessfully': 'કાર્ય સફળતાપૂર્વક કાઢી નાખ્યું',
      'task.markedDeletion': 'કાર્ય કાઢી નાખવા માટે નિશાનિત (પછી સિંક થશે)',
      'task.errorDeleting': 'કાર્ય કાઢવામાં ભૂલ: {error}',
      'patient.addPhoto': 'ફોટો ઉમેરો',
      'patient.patientName': 'દર્દીનું નામ',
      'patient.age': 'ઉંમર',
      'patient.address': 'સરનામું',
      'patient.dateOfBirth': 'જન્મ તારીખ',
      'patient.selectDate': 'તારીખ પસંદ કરો',
      'patient.gender': 'લિંગ',
      'patient.female': 'સ્ત્રી',
      'patient.male': 'પુરુષ',
      'patient.other': 'અન્ય',
      'patient.saveData': 'દર્દીનું ડેટા સાચવો',
      'patient.pleaseAddPhoto': 'કૃપા કરીને દર્દીનો ફોટો ઉમેરો',
      'patient.invalidName': 'કૃપા કરીને દર્દીનું માન્ય નામ દાખલ કરો',
      'patient.invalidAge': 'કૃપા કરીને 1 થી 130 વચ્ચે માન્ય ઉંમર દાખલ કરો',
      'patient.invalidAddress': 'કૃપા કરીને સંપૂર્ણ સરનામું દાખલ કરો',
      'patient.invalidPhone': 'કૃપા કરીને માન્ય 10 અંકનો ફોન નંબર દાખલ કરો',
      'patient.invalidDob': 'કૃપા કરીને માન્ય જન્મતારીખ પસંદ કરો',
      'patient.saveSuccessOnline': 'દર્દીની માહિતી સફળતાપૂર્વક સાચવી અને સિંક થઈ ગઈ',
      'patient.saveSuccessOffline': 'દર્દીની માહિતી ઑફલાઇન સાચવાઈ છે, પછી સિંક થશે',
      'patient.saveFailed': 'દર્દીની માહિતી સાચવી શકાયી નથી. કૃપા કરીને ફરી પ્રયાસ કરો.',
      'patient.takePhoto': 'ફોટો લો',
      'patient.chooseFromGallery': 'ગેલેરીમાંથી પસંદ કરો',
      'patient.saved': 'દર્દી સાચવાયો',
      'patient.savedDetails': 'વિગતો સફળતાપૂર્વક નોંધાઈ',
      'patient.details': 'દર્દી વિગતો',
      'patient.stepFamily': 'પરિવાર',
      'patient.stepPatient': 'દર્દી',
      'patient.stepMedical': 'તબીબી',
      'patient.sessionExpiredLogin': 'સેશન સમાપ્ત થયું છે. કૃપા કરીને ફરીથી લોગિન કરો.',
      'patient.familyRegisteredSuccess': 'પરિવાર સફળતાપૂર્વક નોંધાયો!',
      'patient.saveFailedTryAgain': 'સેવ કરી શકાયું નથી. કૃપા કરીને ફરી પ્રયાસ કરો.',
      'patient.familyInformation': 'પરિવાર માહિતી',
      'patient.headOfFamilyRequired': 'પરિવારના વડા *',
      'patient.enterHeadOfFamily': 'પરિવારના વડાનું નામ દાખલ કરો *',
      'patient.numberOfMembers': 'સભ્યોની સંખ્યા',
      'patient.familyAddressRequired': 'પરિવારનું સરનામું *',
      'patient.enterFamilyAddress': 'પરિવારનું સરનામું દાખલ કરો *',
      'patient.useAddressForAllFamilyMembers': 'આ સરનામું બધા પરિવાર સભ્યો માટે વાપરો',
      'patient.familyInfoHelpText': 'પરિવારના વડાનું નામ અને કુલ સભ્યોની સંખ્યા દાખલ કરો. અલગથી ન જણાવવામાં આવે તો પરિવારનું સરનામું બધાને માટે વપરાશે.',
      'patient.patientNameRequired': 'દર્દીનું નામ *',
      'patient.caste': 'જાતિ',
      'patient.memberWithIndex': 'સભ્ય {index}',
      'patient.changePhoto': 'ફોટો બદલો',
      'patient.removePhoto': 'ફોટો દૂર કરો',
      'patient.removeMemberTitle': 'સભ્ય દૂર કરશો?',
      'patient.removeMemberPromptDefault': 'આ સભ્યને દૂર કરશો?',
      'patient.removeMemberPromptNamed': '{name} ને દૂર કરશો?',
      'patient.remove': 'દૂર કરો',
      'patient.removeThisMember': 'આ સભ્યને દૂર કરો',
      'patient.isPregnant': 'ગર્ભવતી?',
      'patient.expectedDeliveryDate': 'અંદાજિત પ્રસૂતિ તારીખ',
      'patient.monthsOfPregnancy': 'ગર્ભાવસ્થાના મહિના',
      'patient.monthsCount': '{count} મહિના',
      'patient.sameAsFamilyAddress': 'પરિવારના સરનામા જેવું જ',
      'patient.patientAddress': 'દર્દીનું સરનામું',
      'patient.medicalInformation': 'તબીબી માહિતી',
      'patient.privacyDeclined': 'દર્દી તબીબી માહિતી શેર કરવા માંગતા નથી',
      'patient.privacyDeclinedBanner': 'દર્દીએ તબીબી માહિતી શેર કરવાનો ઈનકાર કર્યો છે',
      'patient.selectHealthConditions': 'આરોગ્ય પરિસ્થિતિઓ પસંદ કરો',
      'patient.additionalNotes': 'વધારાની નોંધો',
      'patient.additionalNotesHint': 'દર્દી વિશે વધારાની નોંધો ઉમેરો...',
      'patient.summary': 'સારાંશ',
      'patient.totalPatients': 'કુલ દર્દીઓ: {count}',
      'patient.conditionsSelected': 'પસંદ કરેલી પરિસ્થિતિઓ: {count}',
      'patient.privacyDeclinedSummary': 'ગોપનીયતા: દર્દીએ આરોગ્ય માહિતી શેર કરવાનો ઈનકાર કર્યો',
      'patient.condition.bp': 'BP',
      'patient.condition.elephantiasis': 'હાથીપગો',
      'patient.condition.diabetes': 'ડાયાબિટીસ',
      'patient.condition.heartDisease': 'હૃદયરોગ',
      'patient.condition.asthma': 'અસ્થમા',
      'patient.condition.thyroid': 'થાઈરોઇડ',
      'patient.condition.arthritis': 'સંધિવા',
      'patient.condition.kidney': 'કિડની',
      'patient.condition.liver': 'યકૃત',
      'patient.condition.cancer': 'કેન્સર',
      'patient.ageYears': '{age} વર્ષ',
      'patient.phone': 'ફોન',
      'patient.delete': 'દર્દી કાઢી નાખો',
      'patient.deleteConfirm':
          'આથી દર્દી કાઢી નાખવામાં આવશે. ઓફલાઇન હો તો પછી સિંક કરી શકશો.',
      'patient.markedDeletion':
          'દર્દી કાઢી નાખવા માટે નિશાનિત (ઓનલાઇન પર સિંક થશે)',
      'patient.deletedSuccessfully': 'દર્દી સફળતાપૂર્વક કાઢી નાખ્યો',
      'patient.deleteFailedStatus': 'કાઢવામાં નિષ્ફળ: {status}. પછી સિંક થશે',
      'patient.errorDeleting': 'કાઢવામાં ભૂલ: {error}. પછી સિંક થશે',
      'patients.title': 'દર્દીઓ',
      'patients.searchHint': 'નામ અથવા આઈડીથી શોધો...',
      'patients.quickFilters': 'ઝડપી ફિલ્ટર્સ',
      'patients.allGender': 'બધા લિંગ',
      'patients.others': 'અન્ય',
      'patients.age18to35': 'ઉંમર: 18-35',
      'patients.recentRecords': 'તાજેતરના રેકોર્ડ્સ ({count})',
      'patients.showingAll': 'બધા નોંધાયેલા દર્દીઓ દર્શાવવામાં આવી રહ્યા છે',
      'patients.filtersHint':
          'શોધ સુધારવા ઉપરના ફિલ્ટર્સનો ઉપયોગ કરો અથવા નવો દર્દી રેકોર્ડ ઉમેરો.',
      'patients.newest': 'નવા',
      'patients.oldest': 'જૂના',
      'patients.nameAZ': 'નામ (A-Z)',
      'patients.sortBy': 'ગોઠવો: {sort}',
      'patients.yearsShort': '{age} વર્ષ',
      'phc.keyMetrics': 'મુખ્ય મેટ્રિક્સ',
      'phc.totalPatients': 'કુલ દર્દીઓ',
      'phc.genderDistribution': 'લિંગ વિતરણ',
    },
  };

  String tr(String key, {Map<String, String>? args}) {
    final languageMap =
        _localizedValues[locale.languageCode] ?? _localizedValues['en']!;
    final fallbackMap = _localizedValues['en']!;
    var value = languageMap[key] ?? fallbackMap[key] ?? key;

    if (args != null) {
      for (final entry in args.entries) {
        value = value.replaceAll('{${entry.key}}', entry.value);
      }
    }

    return value;
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return AppLocalizations.supportedLocales.any(
      (supported) => supported.languageCode == locale.languageCode,
    );
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

extension AppLocalizationsContext on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this);
}
